### ISSUE TITLE
handleFileUpload with non acsii file name not working properly

### ISSUE THREAD

**Issue by cvb** [snapframework/snap-core#150]
I'm trying to upload file, which name is utf8 encoded string, and getting string quoted with ".

I found that it can't be properly parsed by Snap.Internal.Parsing.pQuotedString, so as a workaround
I made this patch

https://github.com/cvb/snap-core/commit/e03cb4e05232118bf7e4fb042e963b5dc471750d

**Comment by dzhus** [comment]
Is this the same as #220?

**Comment by mulderr** [comment]
@gregorycollins @dzhus 

There is a new RFC. RFC2388 (August 1998) has been obsolted by RFC7578 (July 2015).

Specifically [this](https://tools.ietf.org/html/rfc7578#section-5.1) seems relevant:

> 5.1.2.  Interpreting Forms and Creating multipart/form-data Data
> 
>    Some applications of this specification will supply a character encoding to be used for interpretation of the multipart/form-data body.  In particular, HTML 5 [W3C.REC-html5-20141028] uses
> 
>    o  the content of a "_charset_" field, if there is one;
>    o  the value of an accept-charset attribute of the form element, if there is one;
>    o  the character encoding of the document containing the form, if it is US-ASCII compatible;
>    o  otherwise, UTF-8.

And later in 5.1.3:

> For this reason, interpreting multipart/form-data (even from conforming generators) may require knowing the charset used in form   encoding in cases where the _charset_ field value or a charset parameter of a "text/plain" Content-Type header field is not supplied.

Apparently the rules have changed. The browsers are definitely not breaking current spec by sending UTF-8 and I think Snap should be updated as well. In fact `otherwise, UTF-8` seems to suggest that UTF-8 is the new default.

**Comment by sopvop** [comment]
IIRC Python requests client does it mime way and snap can't handle it either.

**Comment by mulderr** [comment]
@sopvop Do you by any chance have a link to requests issue for that? I'm trying to see what the current consensus is. Maybe they found a reasonable solution there?

As a summary, relevant RFCs I could find:

* https://tools.ietf.org/html/rfc7578 - in 4.2 states that RFC5987 encoding "MUST NOT be used"
* https://tools.ietf.org/html/rfc6266 - holds that one should use `filename*` for anything non ISO-8859-1
* https://tools.ietf.org/html/rfc5987 - specification of `filename*` encoding
* https://tools.ietf.org/html/rfc2388 - "generally required" to be US-ASCII

In practice:

* Chromium 56
* Firefox 51

will both happily send UTF-8 directly in `filename` without any warning using the simplest form:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <form method="post" enctype="multipart/form-data" action="http://localhost:8000/upload">
      <input type="file" name="the-file">
      <button type="submit">Upload</button>
    </form>
  </body>
</html>
```

Used dev-tools in both browsers and tcpdump to confirm. In short: what @cvb wrote a couple years ago still holds.

Conclusion: `filename*` is dead. Any other special forms of encoding are not being currently used. Browsers will not apply any transformations given UTF-8 filenames and will send them unmodified directly in the `filename` param.

Would you accept a PR that does not assume US-ASCII for Content-Disposition filename value while processing multipart/form-data and keeps everything else as is? Probably by using a different parser [here](https://github.com/snapframework/snap-core/blob/master/src/Snap/Internal/Util/FileUploads.hs#L699).

**Comment by sopvop** [comment]
@mulderr  [here](https://github.com/kennethreitz/requests/issues/3446) is a closed issue for requests, and relevant urllib3 [issue](https://github.com/shazow/urllib3/pull/856).
As I understand it, they haven't implemented any fixes yet.
With requests I just pass a separate header with base64 encoded utf-8 name. You can do something like that with JS i guess, but not with plain form.

**Comment by mulderr** [comment]
Thanks! I do have a workaround in place, so it's not something I need ASAP. The current behavior was very confusing to debug though.

At first glance, in the urllib3 issue, they seem to be discussing what the default should be. But we already have filename returned as `ByteString` - which was I guess a perfect call in anticipation for exactly this kind of problem. We just need to actually allow more then US-ASCII when parsing.

**Comment by gregorycollins** [comment]
This should be fixed now? Please reopen if not.
