### ISSUE TITLE
`rqCaptureParams` for captured variables?

### ISSUE THREAD

**Issue by favonia** [snapframework/snap-core#168]
I'm wondering if we can have a new field `rqCaptureParams` in the `Request` and two separate functions like `rqCaptureParam` and `rqCaptureParams` to access them. I want to make sure, in the handler, that the user is indeed following the rule. I guess this can be done by copying the map in the function `route'` to the field in `Request`.

Related issues: The documentation of `rqParams` should mention variable capturing as well.

Thanks! I really like the overall design of Snap.

PS: My English sucks and so I'm not suggesting they should be named as above.

**Comment by favonia** [comment]
@paluh My PR needs updates but I am occupied by other things now. It would be great if you could do it, and maybe that would accelerate the merging. As far as I remember, both `snap-core` and `snap-server` need to be patched at the same time.

**Comment by favonia** [comment]
Hi, it has been 4 years and I am not able to maintain related pull requests and benchmarks any more. @paluh, do you want to take them over? I will delete the forked repositories for pull requests soon.

**Comment by paluh** [comment]
@favonia I'm sorry, but currently I'm not working on any project written in Snap, so I'm also not able to handle pull requests related to this framework. Thanks!

**Comment by favonia** [comment]
Alright, I will keep this issue open but remove all other stuff. This is not a difficult feature to implement anyways.

**Comment by favonia** [comment]
A few more years have passed. I am closing this due to the lack of interest from the maintainers.
