### ISSUE TITLE
Can't install snap

### ISSUE THREAD

**Issue by jamnut** [snapframework/snap-core#195]
```
$ cabal install snap
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: snap-0.13.2.5 (user goal)
trying: snap-0.13.2.5:-old-base
trying: lens-4.1.2.1 (dependency of snap-0.13.2.5:-old-base)
trying: transformers-compat-0.3 (dependency of lens-4.1.2.1)
trying: transformers-compat-0.3:-transformers2
next goal: transformers (dependency of snap-0.13.2.5)
rejecting: transformers-0.3.0.0/installed-ff2... (conflict:
transformers-compat-0.3:transformers2 => transformers>=0.4 && <0.5)
rejecting: transformers-0.4.1.0 (conflict: snap => transformers>=0.2 && <0.4)
rejecting: transformers-0.3.0.0, 0.2.2.1, 0.2.2.0, 0.2.1.0, 0.2.0.0 (conflict:
transformers-compat-0.3:transformers2 => transformers>=0.4 && <0.5)
rejecting: transformers-0.1.4.0, 0.1.3.0, 0.1.1.0, 0.1.0.1, 0.1.0.0, 0.0.1.0,
0.0.0.0, 0.4.0.0 (conflict: snap => transformers>=0.2 && <0.4)
Backjump limit reached (change with --max-backjumps).

$ cabal --version
cabal-install version 1.20.0.1
using version 1.20.0.0 of the Cabal library 

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

**Comment by victoredwardocallaghan** [comment]
I hit this too

**Comment by lsmag** [comment]
Hi guys, I just installed Cabal and I'm still having this issue, even with `--reorder-goals` and/or `--max-backjumps=-1`.

These are my GHC & Cabal versions:

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.4

    $ cabal --version
    cabal-install version 1.22.0.0
    using version 1.22.0.0 of the Cabal library 

Anytime I run `cabal clean; cabal install -fdevelopment`, I get that *"Backjump limit reached"* error. Trying just *--reorder-goals* will still going to fail sooner or later, but when using `--max-backjumps=-1` the process ends consuming 80% of my RAM and half my CPI until I decide to end it.

I'm already aware that this might be a cabal bug (I'm subscribed to haskell/cabal#1855), but is there any other quickfix I can use to continue my development?

**Comment by mightybyte** [comment]
Try using cabal 1.20.  I've had issues with 1.22, so I have stayed on
1.20.  No guarantees this will solve the problem, but it's worth a try.  To
help any more I'll need a lot more information.  It might be easier to sort
this out on the #snapframework IRC channel.

**Comment by cartazio** [comment]
for people who hit issues that mention transformers, my recommended directions are 
1) add `constraint: transformers installed` to your `~/.cabal/config`
2) `rm -rf ~/.ghc`
3) get back to work :)

**Comment by mightybyte** [comment]
Just to follow up, the solution @cartazio recommended seems to work.  If you don't want to put that constraint in your global config you can add the flag `--constraint='transformers installed'` to your cabal install command.  Also, regarding my above advice against 1.22, it looks like cabal-install-1.22.4.0 may have fixed some of the problems I was seeing with earlier 1.22 versions.

The "transformers installed" constraint seems to be working for everyone I've talked to, so I'm going to close this issue.

**Comment by kosmikus** [comment]
Should it be the case that there are still problems occurring with transformers in current cabal-install releases, I'd like to know about it.

**Comment by mightybyte** [comment]
Snap 0.14 doesn't support GHC 8.  Try building against the most recent code in the github master branch.
