### ISSUE TITLE
io-streams rewrite will break digestive-functors

### ISSUE THREAD

**Issue by ChristopherBiscardi** [snapframework/snap-core#224]
[This change](https://github.com/snapframework/snap-core/commit/c2a69ecdc43547ad84ecc93bee9ea67175138f0e?diff=split#diff-3a1a57f5ee74e1ff11b47928fb5154f5R156) (when using snap core master branch) is currently breaking [these lines](https://github.com/jaspervdj/digestive-functors/blob/master/digestive-functors-snap/src/Text/Digestive/Snap.hs#L66-L67) in digestive-functors-snap.

These are the errors:

```
src/Text/Digestive/Snap.hs:67:9:
    Couldn't match type ‘[(Text, FilePath)]’ with ‘IO (Text, FilePath)’
    Expected type: (Either Snap.PolicyViolationException FilePath
                    -> [Maybe (Text, FilePath)])
                   -> Either Snap.PolicyViolationException FilePath
                   -> IO (Text, FilePath)
      Actual type: (Either Snap.PolicyViolationException FilePath
                    -> [Maybe (Text, FilePath)])
                   -> Either Snap.PolicyViolationException FilePath
                   -> [(Text, FilePath)]
    In the first argument of ‘(.)’, namely ‘fmap catMaybes’
    In the second argument of ‘($)’, namely
      ‘fmap catMaybes . mapM (storeFile tmpDir)’

src/Text/Digestive/Snap.hs:67:26:
    Couldn't match type ‘[(Snap.PartInfo, Either t0 FilePath)]’
                  with ‘Snap.PartInfo’
    Expected type: Snap.PartInfo
                   -> Either Snap.PolicyViolationException FilePath
                   -> [Maybe (Text, FilePath)]
      Actual type: [(Snap.PartInfo, Either t0 FilePath)]
                   -> Either Snap.PolicyViolationException FilePath
                   -> [Maybe (Text, FilePath)]
    In the second argument of ‘(.)’, namely ‘mapM (storeFile tmpDir)’
    In the second argument of ‘($)’, namely
      ‘fmap catMaybes . mapM (storeFile tmpDir)’
```

The signature [on Hackage](https://hackage.haskell.org/package/snap-core-0.9.6.4/docs/src/Snap-Util-FileUploads.html#handleFileUploads) is

```haskell
handleFileUploads ::
       (MonadSnap m) =>
       FilePath
    -> UploadPolicy
    -> (PartInfo -> PartUploadPolicy)
    -> ([(PartInfo, Either PolicyViolationException FilePath)] -> m a)
    -> m a
```

and [on Master](https://github.com/snapframework/snap-core/blob/master/src/Snap/Internal/Util/FileUploads.hs#L127-L135) is

```haskell
handleFileUploads ::
       (MonadSnap m) =>
       FilePath
    -> UploadPolicy
    -> (PartInfo -> PartUploadPolicy)
    -> (PartInfo -> Either PolicyViolationException FilePath -> IO a)
    -> m [a]
```

I have a [patch](https://github.com/ChristopherBiscardi/digestive-functors/commit/3d8836c8144a5f5dec4fac24cf5efcaf9dd47157#diff-d01c88fd44d5133d2779bd9451b559e1R66) on `digestive-functors` which compiles but should we consider this a Snap issue?

**Comment by jaspervdj** [comment]
`digestive-functors-snap` currently requires `snap-core < 0.10`. When the `io-streams`-based changes are released, there will a major version bump in `snap-core` so at that point, a `digestive-functors-snap` release should be made which supports the latest `snap-core`. It is definitly not a Snap issue.

**Comment by ChristopherBiscardi** [comment]
Thanks for checking this out @jaspervdj I'm going to close this one as a result.
