### ISSUE TITLE
Remove Response Show instance

### ISSUE THREAD

**Issue by sopvop** [snapframework/snap-core#233]
I guess historically `responseToString` function in Snap.Test was used to show Response in test.

Currently Show instance for Response already shows body of response, but uses unsafePerformIO
to read from io-streams stream.

``` .haskell
instance Show Response where
  show r = concat [ statusline
                  , hdrs
                  , contentLength
                  , "\r\n"
                  , body
                  ]
    where
      statusline = concat [ "HTTP/1.1 "
                          , show $ rspStatus r
                          , " "
                          , S.unpack $ rspStatusReason r
                          , "\r\n" ]

      hdrs = concatMap showHdr $ H.toList $ renderCookies r
             $ rspHeaders $ clearContentLength r

      contentLength = maybe "" (\l -> concat ["Content-Length: ", show l, "\r\n"] ) (rspContentLength r)

      showHdr (k,v) = concat [ S.unpack (CI.original k), ": ", S.unpack v, "\r\n" ]

      -- io-streams are impure, so we're forced to use 'unsafePerformIO'.
      body = unsafePerformIO $ do
        (os, grab) <- Streams.listOutputStream
        let f = rspBodyToEnum $ rspBody r
        _ <- f os
        fmap (L.unpack . toLazyByteString . mconcat) grab
```

I'm not at all proficient with io-streams, but such use of IO seems bad for me.

I think that Show instance on Response should not show body at all, and `responseToString` should be used for cases when you need to show it.

How should I fix this? Remove unsafePerformIO from Show, or make 

``` .haskell
responseToString = fromShow
```

**Comment by gregorycollins** [comment]
As I mentioned on IRC: Show instance for Response is meant for debugging only, and given the choice of removing Show or `responseToString`, I would rather remove the Show instance.

**Comment by sopvop** [comment]
We can remove printing of body from Show, but show response code and headers.

**Comment by gregorycollins** [comment]
That's fine too actually.

**Comment by mightybyte** [comment]
Did anything get rolled into 1.0 addressing this?

**Comment by sopvop** [comment]
Nope, Show instance for Request still uses [unsafePreformIO](https://github.com/snapframework/snap-core/blob/master/src/Snap/Internal/Http/Types.hs#L732).
And responseToString still grabs body [twice](https://github.com/snapframework/snap-core/blob/master/src/Snap/Internal/Test/RequestBuilder.hs#L959)

I think I've decided not to touch it because it requires fixing a lot of haddocks with examples.

**Comment by gregorycollins** [comment]
@sopvop do you remember where you saw those Haddocks? I'd still like to get rid of the Show instance.

**Comment by sopvop** [comment]
@gregorycollins Examples in Snap.Core all rely on that instance.
For example docs for [pass](http://hackage.haskell.org/package/snap-core-1.0.1.0/docs/Snap-Core.html#v:pass)
```
ghci> :set -XOverloadedStrings
ghci> import qualified Data.Map as M
ghci> import qualified Snap.Test as T
ghci> let r = T.get "/foo/bar" M.empty
ghci> T.runHandler r pass
HTTP/1.1 404 Not Found
server: Snap/test
date: Thu, 07 Aug 2014 13:35:42 GMT

<!DOCTYPE html>
<html>
<head>
<title>Not found</title>
</head>
<body>
<code>No handler accepted "/foo/bar"/code
</body></html>
```
