### ISSUE TITLE
Snap.Util.Upload part processors should fold

### ISSUE THREAD

**Issue by sopvop** [snapframework/snap-core#235]
## Problems

Currently it exports 2 functions for users, a higher level `handleFileUploads` and a bit lower level `handleMultipart`

``` .haskell
handleFileUploads ::
       (MonadSnap m) =>
       FilePath                       -- ^ temporary directory
    -> UploadPolicy                   -- ^ general upload policy
    -> (PartInfo -> PartUploadPolicy) -- ^ per-part upload policy
    -> (PartInfo -> Either PolicyViolationException FilePath -> IO a)
                                      -- ^ user handler (see function
                                      -- description)
    -> m [a]

type PartProcessor a = PartInfo -> InputStream ByteString -> IO a

handleMultipart ::
       (MonadSnap m) =>
       UploadPolicy        -- ^ global upload policy
    -> PartProcessor a     -- ^ part processor
    -> m [a]
```

One of the problems is that if you need any state carried between processing parts, you have to use `IORef`. In my opinion that is not very haskelly.

handleFileUploads has another problem: there is no way to limit number of uploaded files. You can bail out with exception from user handler, but only after downloading extra file (and reading `IORef`).

Current implementation does protect you from inode dos attack by cleaning up temp file after each user handler is run, which is a good thing.

Another problem is that limits on number of _captured_ form inputs are applied after reading the body, though maybe I'm missing some laziness [there](https://github.com/snapframework/snap-core/blob/f1b24eb292477e06d65120f2141c6b29341ceddb/src/Snap/Internal/Util/FileUploads.hs#L237). 

``` .haskell
handleMultipart = do
    ...
    captures <- runRequestBody (proc bumpTimeout boundary partHandler)
    procCaptures captures id
```

Which somewhat limits the effectiveness of protection from form inputs flood. 

There is no limit on whole request size, only limits on speed and parts size.

Last two problems can be fixed without changing signatures.
## Proposal

So my proposal is to change the types to:

``` .haskell
type PartProcessor s = PartInfo -> InputStream ByteString -> s > IO s

handleMultipart ::
       (MonadSnap m) =>
       UploadPolicy        -- ^ global upload policy
    -> PartProcessor s     -- ^ part processor
    -> s -- ^ state seed
    -> m s
```

Which makes PartProcessor something like  `StateT s IO ()`, and so you can carry state when processing parts. This will also help with implementing better limits on form params capture, number of files and sizes.

Alternatively we can make PartProcessor an `m` monad, like

``` .haskell
type PartProcessor m a = PartInfo -> InputStream ByteString ->  m a

handleMultipart ::
       (MonadSnap m) =>
       UploadPolicy        -- ^ global upload policy
    -> PartProcessor m a     -- ^ part processor
    -> m [a]
```

And `monad-control` allows such implementation to be well behaved even if `m` monad is short-circuiting like `Snap` is. That would somewhat complicate implementation though. Also if say `Snap` monad does `pass`, there is no much you can do after, because of partially read body (This is actually a bigger problem of snap mixing routing and handling in same type). That would also make it a bit harder to reason about code.

`handleFileUploads` signature would be changed accordingly.

**Comment by sopvop** [comment]
Just to be clear - the proposed state threading in PartProcessor is for cleaner more general, *functional* and cleaner interface. To avoid unnecessary IORefs. Not only for counting files.

**Comment by mightybyte** [comment]
These changes sound good to me, but I'd prefer if it could be done by adding new exported symbols instead of changing existing ones.

Maybe something like:

```haskell
type StatefulPartProcessor ...
handleMultipart' ...
```

...then implement the existing handleMultipart on top of that.  What do you think?  I would definitely be interested in a pull request like this.  I'm not sure which of your proposals I prefer, the explicit state one or the arbitrary monad one.  The explicit state one seems more complicated on the surface, but I think it's probably easier to use correctly since you don't have to worry about short-circuiting concerns and `monad-control`.

Thoughts?

**Comment by sopvop** [comment]
Maybe something like this
~~~haskell
type PartFold s = PartInfo -> InputStream ByteString -> s > IO s

foldMultipart ::
       (MonadSnap m) =>
       UploadPolicy        -- ^ global upload policy
    -> PartFold s     -- ^ part processor
    -> s -- ^ initial state
    -> m s
~~~

Of course, if you get an exception while handling upload, you don't get the `s` part with it. So to clean up you would still need some kind of IORef.

And I'm not sure what type a better `handleFileUploads` should have.

**Comment by mightybyte** [comment]
This looks reasonable to me.  However, if you still have to use an IORef, do you think we gain enough to make this worth it?

**Comment by sopvop** [comment]
Well, that would allow us to implement proper form-data limiting and dealing with form inputs more cleanly. However the file storage would still need something more clever. Like 
```haskell
withTemporaryStore :: MonadBaseControl m => FilePath -> ((PartInfo -> InputStream ByteString -> IO FilePath) -> m a) -> m a

runUploadsHighLevel :: MonadSnap => (PartInfo -> InputStream ByteString -> IO FilePath) -> m (Map ByteString (Either [ByteString] [FilePath])
```
Or something more general.

**Comment by mightybyte** [comment]
Sounds good.  The overall goal for this module is that it should give users a way to get robust and secure file uploads and take away as many of the possibilities for mistakes/vulnerabilities as possible.  Like I mentioned before, the other big concern is backwards compatibility.  It sounds like you have a pretty compelling case for these changes, so I'm definitely interested in seeing a pull request for these ideas.

**Comment by gregorycollins** [comment]
This issue can be closed right?
