### ISSUE TITLE
URI path segments being decoded like query string elements

### ISSUE THREAD

**Issue by tsloughter** [snapframework/snap-core#245]
For a route `"/posts/:category"` the result of `getParam "category"` from a request with the path `/posts/c++` is `c` instead of `c++`. 

Since `+` is a legal character in a uri path segment it shouldn't replace them with spaces like it would in a query string.

**Comment by gregorycollins** [comment]
Hi,

I'm sorry, the decision we made when we designed this is that route captures do a url decode. Changing it now would break a lot of existing users. If you want to improve it, you could extend the routes module to use a different prefix character besides ":" to mean "capture but don't url-decode" -- I would definitelyu take a pull request for that.
