### ISSUE TITLE
Export compressibleMimeTypes from Snap.Util.Gzip

### ISSUE THREAD

**Issue by cimmanon** [snapframework/snap-core#250]
I would like to add SVGs and ICOs to the list of file types compressed with gzip, but there doesn't appear to be a convenient way to do this.  It looks like I should be able to do this by using `withCompression'` and passing in a Set of mime types, but compressibleMimeTypes is not exposed by the module so I end up having to repeat information that already exists.

**Comment by gregorycollins** [comment]
This is exported from Snap.Util.GZip now.
