### ISSUE TITLE
no output with test -p 8080 quick start tutorial 

### ISSUE THREAD

**Issue by rwobben** [snapframework/snap-core#252]
Hello, 

Im doing the quick start so I did 

- mkdir test 
- cd test 
- snap init barebones 
- cabal  install
- test -p 8080 

I expected to see output and can see my new site.
But I see the prompt agan and when I goto http://localhost:8080 I see no output.

**Comment by mightybyte** [comment]
Most shells have a built-in test command.  I'd recommend trying a different project name.

```
mkdir mytest
cd mytest
snap init barebones
cabal install
mytest -p 8080
```

I just tried this and it worked fine for me.

**Comment by rwobben** [comment]
Thanks, It worked here also. I now see hello world as text in the browser.
Case closed
