### ISSUE TITLE
snap failed to install on haskell platform 8.0.1

### ISSUE THREAD

**Issue by KeesBleijenberg** [snapframework/snap-core#258]
I removed everything from GHC from my windows 7 64 bits machine and installed the haskell platform 8.0.1. Then i did cabal -v install snap and I get:
"D:\Program Files\Haskell Platform\8.0.1\lib\extralibs\bin\alex.exe" "--version"
"C:\Users\kees\AppData\Roaming\cabal\bin\cpphs.exe" "--version"
"D:\Program Files\Haskell Platform\8.0.1\mingw\bin\gcc.exe" "-dumpversion"
looking for tool haddock near compiler in D:\Program Files\Haskell
Platform\8.0.1\bin
found haddock in D:\Program Files\Haskell Platform\8.0.1\bin\haddock.exe
"D:\Program Files\Haskell Platform\8.0.1\bin\haddock.exe" "--version"
"D:\Program Files\Haskell Platform\8.0.1\lib\extralibs\bin\happy.exe" "--version"
"D:\Program Files\Haskell Platform\8.0.1\bin\hpc.exe" "version"
looking for tool hsc2hs near compiler in D:\Program Files\Haskell
Platform\8.0.1\bin
found hsc2hs in D:\Program Files\Haskell Platform\8.0.1\bin\hsc2hs.exe
"D:\Program Files\Haskell Platform\8.0.1\bin\hsc2hs.exe" "--version"
"D:\Program Files\Haskell Platform\8.0.1\lib\extralibs\bin\HsColour.exe" "-version"
"D:\Program Files\Haskell Platform\8.0.1\bin\ghc.exe" "-c" "D:\Temp\4118467.c" "-o" "D:\Temp\633426500.o"
"D:\Program Files\Haskell Platform\8.0.1\mingw\bin\ld.exe" "-x" "-r" "D:\Temp\633426500.o" "-o" "D:\Temp\1916915724.o"
"D:\gtk2\bin\pkg-config.exe" "--version"
Reading available packages...
"D:\gtk2\bin\pkg-config.exe" "--list-all"
"D:\gtk2\bin\pkg-config.exe" "--modversion" "libpng14" "cairo-win32" "cairo" "fontconfig" "gail" "gtk+-win32-2.0" "cairo-pdf" "pangowin32" "gio-2.0" "freetype2" "cairo-gobject" "cairo-ps" "gdk-win32-2.0" "libpng" "gobject-2.0" "pixman-1" "pangocairo" "cairo-win32-font" "cairo-svg" "cairo-fc" "cairo-png" "glib-2.0" "gmodule-2.0" "pango" "gthread-2.0" "gio-windows-2.0" "gdk-2.0" "gtk+-2.0" "cairo-ft" "atk" "gdk-pixbuf-2.0" "gmodule-no-export-2.0" "pangoft2"
Choosing modular solver.
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: snap-0.14.0.7 (user goal)
trying: base-4.9.0.0/installed-4.9... (dependency of snap-0.14.0.7)
next goal: template-haskell (dependency of snap-0.14.0.7)
rejecting: template-haskell-2.11.0.0/installed-2.1...,
template-haskell-2.11.0.0 (conflict: snap => template-haskell>=2.2 && <2.11)
rejecting: template-haskell-2.10.0.0 (conflict:
base==4.9.0.0/installed-4.9..., template-haskell => base==4.8.*)
rejecting: template-haskell-2.9.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.7.*)
rejecting: template-haskell-2.8.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.6.*)
rejecting: template-haskell-2.7.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.5.*)
rejecting: template-haskell-2.6.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.4.*)
rejecting: template-haskell-2.5.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.3.*)
rejecting: template-haskell-2.4.0.1 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base==4.2.*)
rejecting: template-haskell-2.4.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base>=3 && <4.3)
rejecting: template-haskell-2.3.0.1, template-haskell-2.3.0.0,
template-haskell-2.2.0.0 (conflict: base==4.9.0.0/installed-4.9...,
template-haskell => base<4.3)
Dependency tree exhaustively searched.

**Comment by prashanthsadasivan** [comment]
I am also experiencing this same issue on mac OSX el capitan.

**Comment by mightybyte** [comment]
Snap 0.14 doesn't support GHC 8.  Try building against the most recent code
in the github master branch.

**Comment by KeesBleijenberg** [comment]
As suggested by mightybyte I want to install the latest version from github. I'am using win7 64 bits. Ghc version 8.0.1. I'am new to git. 

In msys I did
cd /d/testSnap
git clone https://github.com/snapframework/snap.git
cd ./snap
git submodule update --init --recursive
./init-sandbox.sh
No errors. And then
cabal install
I get the error message below.

Kees

Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: snap-1.0.0.0 (user goal)
trying: time-1.6.0.1/installed-1.6... (dependency of snap-1.0.0.0)
next goal: snap-server (dependency of snap-1.0.0.0)
rejecting: snap-server-1.0.0.0 (conflict: time==1.6.0.1/installed-1.6...,
snap-server => time>=1.0 && <1.6)
rejecting: snap-server-0.9.5.1, snap-server-0.9.5.0, snap-server-0.9.4.6,
snap-server-0.9.4.5, snap-server-0.9.4.4, snap-server-0.9.4.3,
snap-server-0.9.4.2, snap-server-0.9.4.1, snap-server-0.9.4.0,
snap-server-0.9.3.4, snap-server-0.9.3.3, snap-server-0.9.3.1,
snap-server-0.9.3, snap-server-0.9.2.4, snap-server-0.9.2.3,
snap-server-0.9.2.2, snap-server-0.9.2.1, snap-server-0.9.2,
snap-server-0.9.0, snap-server-0.8.1.1, snap-server-0.8.1,
snap-server-0.8.0.1, snap-server-0.8.0, snap-server-0.7.0.1, snap-server-0.7,
snap-server-0.6.0.1, snap-server-0.6.0, snap-server-0.5.5, snap-server-0.5.4,
snap-server-0.5.3.1, snap-server-0.5.3, snap-server-0.5.2,
snap-server-0.5.1.4, snap-server-0.5.1.3, snap-server-0.5.1.2,
snap-server-0.5.1.1, snap-server-0.5.1, snap-server-0.5.0, snap-server-0.4.3,
snap-server-0.4.2, snap-server-0.4.1, snap-server-0.4.0.2,
snap-server-0.4.0.1, snap-server-0.4.0, snap-server-0.3.1.1,
snap-server-0.3.1, snap-server-0.3.0, snap-server-0.2.16.2,
snap-server-0.2.16.1, snap-server-0.2.16, snap-server-0.2.15.1,
snap-server-0.2.15, snap-server-0.2.14.1, snap-server-0.2.14,
snap-server-0.2.13.3, snap-server-0.2.13.2, snap-server-0.2.13.1,
snap-server-0.2.13, snap-server-0.2.12, snap-server-0.2.11,
snap-server-0.2.10.2, snap-server-0.2.10.1, snap-server-0.2.10,
snap-server-0.2.9, snap-server-0.2.8.1, snap-server-0.2.8,
snap-server-0.2.7.2, snap-server-0.2.7.1, snap-server-0.2.7,
snap-server-0.2.6, snap-server-0.2.5, snap-server-0.2.4, snap-server-0.2.2,
snap-server-0.2.1, snap-server-0.1.4, snap-server-0.1.3, snap-server-0.1.2,
snap-server-0.1.1 (conflict: snap => snap-server>=1.0 && <1.1)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by KeesBleijenberg** [comment]
I removed all ghc stuff and installed stack.
This time, the installation of hasql works fine. No pop ups complaining about missing dll's. The test program now compiles without errors.

After installationI tried to compile another test program at https://github.com/dgonyeo/blog-hasql-example but that failed. 
Still, progress!

Kees

**Comment by gspia** [comment]
Without checking this, snapframework/snap#170 might be related: the git cmd does not seem point to the master, and by asking master (see the git cmd there), you may get this to install in a sandboxed environment.

**Comment by mightybyte** [comment]
We just released Snap 1.0.  It should resolve this issue.
