### ISSUE TITLE
Please release a new version of snap-core to Hackage which builds properly

### ISSUE THREAD

**Issue by tebello-thejane** [snapframework/snap-core#259]
My eyes might be deceiving me, but it would appear that the version of `snap-core` on Hackage has a dependency on `MonadCatchIO-transformers` -- a deprecated library which hasn't been updated in a bit -- and this therefore causes `snap-core` on Hackage to fail to build with GHC8.

The version on Hackage is 11 months old. Can we please release a new version which works on GHC8, since these issues have already been fixed on the Git repo?

In particular, `snap-sever` fails to build in GHC8 from Hackage, which causes the important `ekg` package to fail -- which is a terrible situation indeed.

**Comment by hesiod** [comment]
You might want to have a look at #256.

**Comment by mightybyte** [comment]
It usually takes awhile to get all the pieces in place to support a new GHC version.  We are working on it and planning to release Snap 1.0 on August 7 at the end of Hac Boston.

**Comment by mightybyte** [comment]
Also, if you would like to contribute, we have a wiki with the 1.0 todo list here:

https://github.com/snapframework/snap/wiki/1.0-TODO-List

**Comment by mightybyte** [comment]
Just released Snap 1.0 which should resolve this.

**Comment by tebello-thejane** [comment]
Excellent! Thanks. 😃
