### ISSUE TITLE
SameSite cookies support

### ISSUE THREAD

**Issue by Pitometsu** [snapframework/snap-core#260]
Any reasons why [SameSite cookies](https://en.wikipedia.org/wiki/HTTP_cookie#SameSite_cookie) native support was not added?

**Comment by sopvop** [comment]
Because only chrome supports it for 2 months?

**Comment by Pitometsu** [comment]
Would it be good idea to add it now?

**Comment by mightybyte** [comment]
At this point I think it's too new and not widespread enough to support in Snap.  After a brief investigation, it looks like you should be able to use SameSite cookies manually via Snap's [headers API](http://hackage.haskell.org/package/snap-core-0.9.8.0/docs/Snap-Core.html#g:9).
