### ISSUE TITLE
Websocket closes prematurely in 1.0 but is okay in 0.9.2

### ISSUE THREAD

**Issue by henrylaxen** [snapframework/snap-core#264]
Dear Snappers,

I have been trying to get to the bottom of this for three or four days
now, and so far no joy.  I am not sure if the problem is with snap or
websockets-snap, but I can make it happen consistently.  I have
created two stack repositories to demonstrate the issue.  In the
wsText-6.22 repo, I'm using stack lts-6.22. See the cabal file for the
specific snap and websocket versions.  Everything works fine.  The
Main.hs program just waits forever for the client.js javascript
program to send it a message after the websocket connection is
established and a couple of messages are sent back and forth.  However
when I run the exact same code  with the lts-7.4 stack, the
connection is closed after about 20 seconds.  Things I have tried
include calling the snap function extendTimout before the
runWebSocketsSnap call, putting the forever $ do
send/receive loop in a separate forkIO function, adding a threadDelay
between the WS.receive and WS.send, but nothing seems to make any
difference.  To see the problem, build the two repos using stack, and
run:

stack exec wsTest

then in your browser navigate to localhost:8000 and open your
javascript console.

This is a real show stopper for me for upgrading to Snap 1.0 and
friends.  If there is anything I can do to help you guys track this
down, please let me know.
Best wishes,
Henry Laxen

[snapWebsocketProblem.zip](https://github.com/snapframework/snap-core/files/537956/snapWebsocketProblem.zip)

**Comment by mightybyte** [comment]
@gregorycollins Do you think this is more likely to be a snap thing or a websockets-snap thing?

**Comment by henrylaxen** [comment]
Dear Doug,

I have no way to know, sorry.  I'm just looking in from the outside.
Best wishes,
H

>>>>> "Doug" == Doug Beardsley <notifications@github.com> writes:

    Doug> @gregorycollins Do you think this is more likely to be a snap thing or a
    Doug> websockets-snap thing?

    Doug> —
    Doug> You are receiving this because you authored the thread.
    Doug> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Nadine and Henry Laxen   The rest is silence
Villa Alta #6            
Calle Gaviota #10        Never try to teach a pig to sing
Chapala                  It wastes your time  
+52 (376) 765-3181       And it annoys the pig

**Comment by imalsogreg** [comment]
#### A workaround

I tried adding `setInterval( (w) => {if (w.readyState ==1){ w.send('ping');} }, 10000, ws );` at the bottom of your document.ready function. This holds the connection open with fake pings.

#### Some clues for debugging

```
opts = WS.defaultConnectionOptions { WS.connectionOnPong = print "PONG!" }
s/runWebSocketsSnap/runWebSocketsSnapWith opts
```

This change gives us some logging on the server's Pong handling. (The config option doesn't interfere with the internal behavior of websockets-snap to a pong - which tickles the connection to hold it open a bit longer).

I made the this change in (A) your example server, and (B) the example websockets server that ships with websockets-snap. (A) never prints "PONG!" while (B) prints "PONG!" once every 30 seconds (in response to the websockets-snap's Pings, which happen every 30 seconds). This was built against snap 1.0.0.1.

In the javascript console of your example, I see traces of a Pong being sent. So I believe the server is the piece at fault. Why there is a difference between LTS 6.2 and 7.4, I don't know.

@jaspervdj - do you mind taking a look? The server in question looks like:

```
main :: IO ()
main = httpServe conf app
  where
    conf =
      setErrorLog  ConfigNoLog $
      setAccessLog ConfigNoLog $
      defaultConfig

opts = WS.defaultConnectionOpts { WS.connectionOnPong = print "PONG!" }

handleSocketTest :: Snap ()
handleSocketTest = runWebSocketsSnapWith opts (\pending -> do
  connection <-  WS.acceptRequest pending
  watch ("enter handlerSocket" :: Text)
  _ <- forever $ do
    msg <- getMessage connection
    WS.sendTextData connection ("ok" :: Text)
    WS.sendTextData connection (pack . show $ msg)
  return () )

getMessage :: WS.Connection -> IO WS.Message
getMessage connection = do
  before <- getCurrentTime
  watch ("Before receive" :: Text, before)
  message <- WS.receive connection
    `catch` handleReceiveError
  watch ("Received" :: Text, show message)
  after <- getCurrentTime
  watch ("After receive" :: Text, after)
  return message

handleReceiveError :: SomeException -> IO WS.Message
handleReceiveError e = do
  watch ("handleReceiveError" :: Text, e)
  return (WS.DataMessage (WS.Text "ReceiveError"))
```

**Comment by mightybyte** [comment]
@henrylaxen Oh, I'm sorry.  I didn't mean that question for you.  I was asking @gregorycollins.

**Comment by henrylaxen** [comment]
No problem Doug.  I tried the "workaround" greg sent me and can confirm it
works, even when I extend the js interval to 20000.  It closes again if the js
interval is extended to 21000.  I went into Network.WebSockets.Snap and
changed 

--    stream <- WS.makeStream (tickle (max 20) >> Streams.read readEnd)
      stream <- WS.makeStream (Streams.read readEnd)

but it made no difference.  I really hoped that was the culprit, but alas no.
Best wishes,
Henry Laxen

>>>>> "Doug" == Doug Beardsley <notifications@github.com> writes:

    Doug> @henrylaxen Oh, I'm sorry. I didn't mean that question for you. I was asking 
    Doug> @gregorycollins.

    Doug> —
    Doug> You are receiving this because you were mentioned.
    Doug> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Nadine and Henry Laxen   The rest is silence
Villa Alta #6            
Calle Gaviota #10        Never try to teach a pig to sing
Chapala                  It wastes your time  
+52 (376) 765-3181       And it annoys the pig

**Comment by henrylaxen** [comment]
Dear Greg and Doug,

I played around with it a little more and changed
   stream <- WS.makeStream (tickle (max 20) >> Streams.read readEnd)
   to
   stream <- WS.makeStream (tickle (max 60) >> Streams.read readEnd)

and was able to remove  the
  setInterval( (w) => {if (w.readyState == 1){ w.send('ping');} }, 10000, ws );
workaround completely.  Apparently the tickle timeout was set to low.  Perhaps
there was a reason for this, I don't know.

Best wishes,
Henry Laxen


-- 
Nadine and Henry Laxen   The rest is silence
Villa Alta #6            
Calle Gaviota #10        Never try to teach a pig to sing
Chapala                  It wastes your time  
+52 (376) 765-3181       And it annoys the pig

**Comment by mightybyte** [comment]
@henrylaxen Ok, great.  That means that this is a potential issue for the websockets-snap package and not a snap-core problem, so I'm going to close this issue.

Pinging @jaspervdj

**Comment by jaspervdj** [comment]
This is indeed a websockets problem.  Sorry for the late reply.
