### ISSUE TITLE
Tricky naming conflict with Snapcraft Snap

### ISSUE THREAD

**Issue by xuanruiqi** [snapframework/snap-core#278]
So, Ubuntu 18.04 LTS now ships with the new package management tool Snap, which is also used across other Linux distros. Now there's a tricky name conflict here.

Perhaps the solution is to rename the Snap Framework binary to something like `snaphs`, but it would be up to the Snap team to decide that.

**Comment by mightybyte** [comment]
Our binary has been using that name for something like 8 years.  Not really interested in changing just because of some new thing that Ubuntu has.  If it's a problem for them, they should address it in their distro.
