### ISSUE TITLE
Do Params handle percent decoding?

### ISSUE THREAD

**Issue by kozross** [snapframework/snap-core#300]
For a function like [`rqParams`](http://hackage.haskell.org/package/snap-core-1.0.4.2/docs/Snap-Core.html#v:rqParams), can I assume that percent decoding has been handled, or do I have to handle it myself? The documentation wasn't clear to me on this point.

**Comment by gregorycollins** [comment]
Yes - https://github.com/snapframework/snap-server/blob/b2a888230e107046404b047ff3b8690a592f124c/src/Snap/Internal/Http/Server/Session.hs#L377
