### ISSUE TITLE
Stackage maintainership

### ISSUE THREAD

**Issue by andreasabel** [snapframework/snap-core#334]
@cydparser  Would you take the Stackage maintainership of packages from the snap universe?
You would get then be alerted in case dependency updates are needed, e.g.
- https://github.com/commercialhaskell/stackage/issues/7309

**Comment by cydparser** [comment]
Hi, I'm not interested in receiving more notifications. Hackage already sends me emails about outdated dependencies, but I have very little time to devote to these packages.
