### ISSUE TITLE
Misparsed requests hang

### ISSUE THREAD

**Issue by antonvs** [snapframework/snap-core#36]
The fileServe functions do not match a URI that is correctly encoded with %20 for spaces, so are unable to serve files with spaces in their names.  

This is presumably related to issue #33, however I thought it was worth a separate issue since it prevents Snap from serving certain otherwise ordinary files.

Also, a much more minor related issue is that using a URI containing unencoded spaces results in an empty response from Snap after 30 seconds, presumably because the request line was not successfully parsed.  By comparison, Apache succeeds in parsing such lines immediately, but appears to parse only up to the first space, which then typically results in a 404 error.  I haven't checked the HTTP spec on this - it might be better to returned some sort of "malformed request" error.

**Comment by mightybyte** [comment]
Closing this for cleanup since 1.0 is a huge overhaul.  Feel free to reopen if it's still an issue.
